version: "3.3"
name: spark-cluster

services:
  spark-master:
    image: alexisptr/spark-master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "4040:4040"
    volumes:
      - ./app:/app

  spark-worker-1:
    image: alexisptr/spark-worker
    container_name: spark-worker-1
    ports:
      - "8081:8080"
    depends_on:
      - spark-master
    volumes:
      - ./app:/app

  spark-worker-2:
    image: alexisptr/spark-worker
    container_name: spark-worker-2
    ports:
      - "8082:8080"
    depends_on:
      - spark-master
    volumes:
      - ./app:/app

  pyspark-notebook:
    image: jupyter/pyspark-notebook
    restart: always
    container_name: pyspark-notebook
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    environment:
      - "JUPYTER_TOKEN=pizza"
    volumes:
      - ./app:/home/arthur
